"""cache and corrections

Revision ID: 9d523dbb99d2
Revises: 
Create Date: 2026-10-05 22:08:59.250682

"""
from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '9d523dbb99d2'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('extraction_cache',
    sa.Column('cache_key', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('source_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('fingerprint', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('provider', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('model', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('mime_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('result', sa.JSON(), nullable=True),
    sa.Column('schema_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sqlmodel.sql.sqltypes.UTCDateTime(), nullable=False),
    sa.Column('hit_count', sa.Integer(), nullable=False),
    sa.Column('last_hit_at', sqlmodel.sql.sqltypes.UTCDateTime(), nullable=True),
    sa.PrimaryKeyConstraint('cache_key')
    )
    op.create_index(op.f('ix_extraction_cache_fingerprint'), 'extraction_cache', ['fingerprint'], unique=False)
    op.create_index(op.f('ix_extraction_cache_source_hash'), 'extraction_cache', ['source_hash'], unique=False)
    op.create_table('revision',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('source_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('actor', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('note', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('base_fingerprint', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sqlmodel.sql.sqltypes.UTCDateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_revision_source_hash'), 'revision', ['source_hash'], unique=False)
    op.create_table('correction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('revision_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('source_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('base_fingerprint', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('field_path', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('old_value', sa.JSON(), nullable=True),
    sa.Column('new_value', sa.JSON(), nullable=True),
    sa.Column('actor', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('origin', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sqlmodel.sql.sqltypes.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['revision_id'], ['revision.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_correction_revision_id'), 'correction', ['revision_id'], unique=False)
    op.create_index(op.f('ix_correction_source_hash'), 'correction', ['source_hash'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_correction_source_hash'), table_name='correction')
    op.drop_index(op.f('ix_correction_revision_id'), table_name='correction')
    op.drop_table('correction')
    op.drop_index(op.f('ix_revision_source_hash'), table_name='revision')
    op.drop_table('revision')
    op.drop_index(op.f('ix_extraction_cache_source_hash'), table_name='extraction_cache')
    op.drop_index(op.f('ix_extraction_cache_fingerprint'), table_name='extraction_cache')
    op.drop_table('extraction_cache')
    # ### end Alembic commands ###
